image: python:latest
pages:
  stage: deploy
  only:
    - main
  script:
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

pytest:
  stage: test
  only:
    - main
  script:
    - pip install -r requirements-dev.txt
    - pytest
  artifacts:
    paths:
      - test_report.xml

test-python3.7:
  stage: test
  image: python:3.7
  variables:
    PY_VERSION: "3.7"
  script:
    - python${PY_VERSION} -m venv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
    - pytest
  artifacts:
    paths:
      - test_report_py37.xml

test-python3.10:
  stage: test
  image: python:3.10
  variables:
    PY_VERSION: "3.10"
  script:
    - python${PY_VERSION} -m venv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
    - pytest
  artifacts:
    paths:
      - test_report_py310.xml